[package]
name = "minitrace"
version = "0.1.0"
authors = ["Jakob Fischer <jakob@automorph.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
